import yaml
import click
import time
import os
from pathlib import Path
from rich.console import Console
from rich.progress import Progress, SpinnerColumn, TextColumn, BarColumn, TimeRemainingColumn
from readmeai.utils.extract import extract_file_content
from readmeai.utils.llm import generate_doc

console = Console()

def run_docs():
    """
    Generates documentation by processing files listed in doclify.yaml.
    """
    # Fail fast if API key is missing
    if not os.getenv("GOOGLE_API_KEY"):
        console.print("[bold red]Error:[/bold red] GOOGLE_API_KEY environment variable is not set.")
        console.print("Please set it in your terminal or system environment variables before running Doclify.")
        console.print("\n[dim]Example (Windows cmd):[/dim] set GOOGLE_API_KEY=your_key_here")
        console.print("[dim]Example (PowerShell):[/dim]  $env:GOOGLE_API_KEY='your_key_here'")
        return

    config_path = Path("doclify.yaml")
    if not config_path.exists():
        console.print("[bold red]Error:[/bold red] doclify.yaml not found. Run [bold green]doclify init[/bold green] first.")
        return

    try:
        config = yaml.safe_load(config_path.read_text(encoding="utf-8"))
        files = config.get("structure", [])
        
        if not files:
            console.print("[yellow]No files found in docly.yaml structure.[/yellow]")
            return

        documentation = []
        documentation.append("# Project Documentation\n")
        documentation.append(f"Generated by Docly on {time.strftime('%Y-%m-%d %H:%M:%S')}\n")

        processed_count = 0
        skipped_count = 0
        file_summaries = []

        console.print()  # Add padding before progress bar
        with Progress(
            SpinnerColumn(),
            TextColumn("[progress.description]{task.description}"),
            BarColumn(),
            TextColumn("[progress.percentage]{task.percentage:>3.0f}%"),
            TimeRemainingColumn(),
            console=console
        ) as progress:
            task = progress.add_task("[cyan]Analyzing files...", total=len(files))
            
            for file_path in files:
                progress.update(task, description=f"[cyan]Analyzing {file_path}...")
                
                content = extract_file_content(file_path)
                if content.startswith("Error") or content.startswith("File not found"):
                    skipped_count += 1
                    progress.advance(task)
                    continue
                
                # Step 1: Generate Per-File Summary
                try:
                    summary = generate_doc(content, type="code_summary")
                    file_summaries.append(f"## File: {file_path}\n\n{summary}")
                except Exception as e:
                    file_summaries.append(f"## File: {file_path}\n\nError generating summary: {e}")

                processed_count += 1
                progress.advance(task)
                
            # Step 2: Generate Final README from Aggregated Summaries
            if file_summaries:
                progress.update(task, description="[cyan]Generating final README...", total=1, completed=0)
                aggregated_content = "\n\n".join(file_summaries)
                final_readme = generate_doc(aggregated_content, type="final_summary")
            else:
                final_readme = "# Project Documentation\n\nNo valid files were processed."

        readme_path = Path("README.md")
        if readme_path.exists():
            backup_path = Path("README-prev.md")
            readme_path.rename(backup_path)
            console.print(f"[dim]Existing README.md backed up to {backup_path}[/dim]")

        readme_path.write_text(final_readme, encoding="utf-8")

        console.print(f"\n[bold green]Success![/bold green] Documentation generated in [bold blue]{readme_path}[/bold blue]")
    except Exception as e:
        console.print(f"[bold red]Failed to run documentation generation:[/bold red] {e}")
